# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


logging:
    level:
        ROOT: INFO
        tech.jhipster: INFO
        com.kripstanx: INFO
        org.hibernate:
            SQL: INFO
            type.descriptor.sql.BasicBinder: INFO
eureka:
    instance:
        prefer-ip-address: true
    client:
        enabled: false # By default, the JHipster Registry is not used in the "dev" profile
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
spring:
    application:
        name: KripStanx
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use Webpack dev server + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/krips;DB_CLOSE_DELAY=-1
        username: Krips
        password:
    h2:
        console:
            enabled: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: false
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    liquibase:
      contexts: dev
    mvc:
      favicon:
        enabled: false
    messages:
      basename: i18n/messages
      cache-duration: PT1S # 1 second, see the ISO 8601 standard
    thymeleaf:
      check-template-location: true
      prefix: classpath:/templates/
      suffix: .html
      cache: true
      mode: HTML
      encoding: UTF-8
      content-type: text/html

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias kripstanx -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 8443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        key-store-type: PKCS12
#        key-alias: kripstanx
# ===================================================================
server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count"
        allow-credentials: true
        max-age: 1800
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 1 year
                token-validity-in-seconds: 31540000
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: Kripstanx@localhost
        base-url: http://127.0.0.1:9000
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
    async:
        core-pool-size: 4
        max-pool-size: 50
        queue-capacity: 20000
    #swagger:
        #default-include-pattern: /api/.*
        #title: KripStanx API
        #description: KripStanx API documentation
        #version: 0.0.1
        #terms-of-service-url:
        #contact-name:
        #contact-url:
        #contact-email:
        #license:
        #license-url:
    cache:
        ehcache:
            time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
            max-entries: 1000

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# ===================================================================

application:
    allow-multiple-sessions: true
    reservation-period-in-days: 1
    email:
        soa:
            url:
            username:
            password:
            # if the default truststore wouldn't satisfy your needs
            #trust-store:
            #trust-store-password:
            key-store:
            key-store-password:
    default-users:
        - username: admin
          password: $2a$10$gSAhZrxMllrbgj/kkK9UceBPpChGWJA7SYIb1Mqo.n5aNLq1/oRrC
          first-name: Administrator
          last-name: Snow
          email: admin@localhost.com
          authorities:
              - name: ROLE_USER
              - name: ROLE_ADMIN
        - username: admin2
          password: $2a$10$gSAhZrxMllrbgj/kkK9UceBPpChGWJA7SYIb1Mqo.n5aNLq1/oRrC
          first-name: Administrator2
          last-name: Snow
          email: admin2@localhost.com
          authorities:
              - name: ROLE_USER
              - name: ROLE_ADMIN
              - name: ROLE_TECHNICAL
              - name: ROLE_DBA
        - username: user
          password: $2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K
          first-name: User
          last-name: Jones
          email: user@localhost.com
          authorities:
              - name: ROLE_USER
        - username: user2
          password: $2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K
          first-name: User2
          last-name: Jones
          email: user2@localhost.com
          authorities:
              - name: ROLE_USER

management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: ["configprops", "env", "health", "info", "threaddump"]
    endpoint:
        health:
            show-details: when_authorized
    info:
        git:
            mode: full
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
    metrics:
        enabled: false # http://micrometer.io/ is disabled by default, as we use http://metrics.dropwizard.io/ instead

info:
    # Comma separated list of profiles that will trigger the ribbon to show
    display-ribbon-on-profiles: "dev"
